export const HcmOperationType = {
  GET_BALANCE: 'GET_BALANCE',
  FILE_TIME_OFF: 'FILE_TIME_OFF',
  CANCEL_TIME_OFF: 'CANCEL_TIME_OFF',
  BATCH_SYNC: 'BATCH_SYNC',
};

export const HcmOperationStatus = {
  STARTED: 'STARTED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  RETRYABLE_FAILED: 'RETRYABLE_FAILED',
};

export const HcmFailureMode = {
  DOWN: 'DOWN',
  TIMEOUT: 'TIMEOUT',
  INVALID_DIMENSIONS: 'INVALID_DIMENSIONS',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  RANDOM_FAILURE: 'RANDOM_FAILURE',
};

export const HcmClientErrorCode = {
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_DIMENSIONS: 'INVALID_DIMENSIONS',
  HCM_UNAVAILABLE: 'HCM_UNAVAILABLE',
  UNKNOWN: 'UNKNOWN',
};
